# Use Node.js as the base image
FROM node:22

# Set working directory inside container
WORKDIR /app

# Copy package.json and install dependencies first (for caching)
COPY package.json package-lock.json ./
RUN npm install

COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=$API_URL 
RUN npm run build

COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

CMD ["/bin/sh", "entrypoint.sh"]