# Use Node.js as the base image
FROM node:22

# Set working directory inside container
WORKDIR /app

# Copy package.json and install dependencies first (for caching)
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app
COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$API_URL 

# Expose Vite's ports
EXPOSE 5173 24678

# Start the Vite dev server
CMD ["npm", "run", "dev"]
