networks:
  internal_network:
    driver: bridge

services:

  wordpress:
    image: wordpress:latest
    container_name: blog
    networks:
      - internal_network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password1
      WORDPRESS_DB_NAME: grf
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: db
    networks:
      - internal_network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1
      MARIADB_DATABASE: grf
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - internal_network
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
      - "24678:24678"
    working_dir: /app
    networks:
      - internal_network
    command: ["npm", "run", "dev"]
    environment:
      CHOKIDAR_USEPOLLING: true 
      WDS_SOCKET_PORT: 5173
      API_URL: "http://api.localhost"
    stdin_open: true
    tty: true
    depends_on:
      - db

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    container_name: api
    volumes:
      - ./backend:/app
    networks:
      - internal_network
    restart: always    
    environment:
      DEBUG: True
      PYTHONUNBUFFERED: 1
    depends_on:
      - db


volumes:
  db_data:
  wordpress_data: