FROM python:latest

WORKDIR /app

COPY requirements.txt .

RUN python -m pip install --no-cache-dir -r requirements.txt
RUN python -m pip install watchfiles

COPY . .

EXPOSE 8000

CMD ["python", "./gfunbackend/manage.py", "runserver", "0.0.0.0:8000", "--noreload"]