# Generated by Django 5.1.5 on 2025-01-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Game Name')),
                ('mobile_friendly', models.BooleanField(verbose_name='Mobile Friendly')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Header image')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
            ],
        ),
    ]
